title: test site enno
description: description of ennos test site
theme: jekyll-theme-leap-day


collections:
  tags:
    output: true

defaults:
  - scope:
      path: "_tags"
      type: "tags"
    values:
      layout: "tags"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
