title: test site enno
description: description of ennos test site
# theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

collections_dir: collections
collections:
  tags:
    output: true

defaults:
  - scope:
      path: "_tags"
    values:
      layout: "tags"

  - scope:
      path: ""
    values:
      layout: "default"
