title: test site enno
description: description of ennos test site
theme: jekyll-theme-cayman

collections:
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tags"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
